######################################################################
# Automatically generated by qmake (2.01a) Di 28. Aug 13:37:36 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
RC_FILE += myapp.rc
RESOURCES += pzg.qrc

# CONFIG += console


# Input
HEADERS += pzgtools.h
FORMS += pzgtools.ui
SOURCES += main.cpp pzgtools.cpp
